### Итог занятия

На занятии узнали как скачать библиотеку NumPy в редактор кода, а также как ее импортировать для работы. Познакомились с понятием массива, двумерного массива, разобрали типы данных - int8, int16, int32, int64, float8, float16, float32, float64. Изучили работу функций .sum(), .max(), .min(), .shape, .reshape(), .ndim(), .size.

**Домашнее задание**

В качестве ДЗ тебе нужно создать два массива одинакового размера и попробовать сложить их, умножить один массив на число, возвести его в степень и попробовать стандартные арифметические операции. Посмотри на результат и проанализируй его. Какая логика реализует ту, или иную операцию?

### Знакомство с NumPy

NumPy — библиотека с открытым исходным кодом для языка программирования Python. Возможности: поддержка многомерных массивов; поддержка высокоуровневых математических функций, предназначенных для работы с многомерными массивами.

![](https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/1024px-NumPy_logo_2020.svg.png)


### Установка NumPy

In [ ]:
# первичная загрузка библиотеки для локального пользования
!pip install numpy

In [ ]:
# импортирование библиотеки для работы
import numpy as np

### Работа в NumPy


In [ ]:
# создаем одномерный массив
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [ ]:
# создаем многомерный массив

b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Атрибуты массива NumPy

In [ ]:
# узнаем количество измерений в массиве
print(b.ndim)

2


In [ ]:
# узнать размер массива в виде количества строк и столбцов

c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

print(c.shape) # первая координата - число строк, вторая - число столбцов

(4, 3)


In [ ]:
# узнаем количество элементов в массиве

print(c.size)

12


In [ ]:
# узнаем тип данных элементов в массиве

# int - целое число
# float - число с плавающей точкой

# int8, int16, int32, int64
# float8, float16, float32, float64

# берем цифру при типе данных, для данного типа данных в него входят числа в диапазоне от -1*2**(n/2) <= x <= 2**(n/2)-1
# int16 -> -256 <= x <= 255

print(c.dtype)

c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], dtype=float)

print(c.dtype)

int64
float64


In [ ]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(c.dtype)

c = c.astype('int8')
print(c)
print(c.dtype)

int64
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
int8


In [ ]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], dtype='int16')
print(c)
print(c.dtype)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
int16


In [ ]:
# узнаем сумму элементов в массиве
# sum() - встроеннаяя функция для суммирования -> list1 -> sum(list1)

print(c.sum())

78


In [ ]:
# получаем минимальное число в массиве
print(c.min())
# получаем максимальное число в массиве
print(c.max())

1
12


In [ ]:
# зададим массив случайно

d = np.random.random((3, 3))
print(d)

[[0.95060148 0.55862557 0.61755891]
 [0.02382338 0.18986042 0.78427868]
 [0.04690128 0.04222851 0.38698914]]


In [ ]:
# многомерный массив из нулей

e = np.zeros((3, 4))
print(e)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# многомерный массив из единиц

e = np.ones((3, 4))
print(e)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# массив с случайными числам

f = np.empty((4, 4))
print(f)

[[4.70158880e-310 0.00000000e+000 4.39718425e-322             nan]
 [9.46350096e+218 4.77800043e+180 9.75024312e+199 2.93301537e+222]
 [1.81450402e-152 9.48701663e+170 2.43624408e+232 8.54655291e-072]
 [2.28646217e+232 2.31460460e-152 3.02389982e-110 4.03179200e-312]]


In [ ]:
# массив с диапазоном между числами - аналог функции ragne

f = np.arange(50, 76, 5)
print(f)

[50 55 60 65 70 75]


In [ ]:
# создаем массив, в котором элементы находятся в некотором диапазоне

f = np.linspace(50, 80, 4)

print(f)

[50. 60. 70. 80.]


In [ ]:
# изменяем количество измерений массива

f = np.arange(1, 16)
print(f)

f = f.reshape((5, 3))
print(f)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


#### 14.06.24


#### Сложение массивов (матриц)

![](https://www.yotx.ru/Images/matrix-addition-2.gif)

In [ ]:
arr1 = np.array([[0, 1, 2], [8, 9 , 0]])
arr2 = np.array([[10, 11, 12], [80, 90, 56]])

print(arr1, arr2, sep='\n\n')
print('\n', arr1+arr2)

[[0 1 2]
 [8 9 0]]

[[10 11 12]
 [80 90 56]]

 [[10 12 14]
 [88 99 56]]


#### Вычитание массива (матрицы)

![](https://www.yotx.ru/Images/matrix-subtraction-2.gif)

In [ ]:
print(arr1, arr2, sep='\n\n')
print('\n', arr1-arr2)

[[0 1 2]
 [8 9 0]]

[[10 11 12]
 [80 90 56]]

 [[-10 -10 -10]
 [-72 -81 -56]]


#### Умножение массива (матрицы) на число

![](https://microexcel.ru/wp-content/uploads/2021/06/umnojenie-matritsy-na-chislo-1.png)

In [ ]:
print(arr1, end='\n\n')
print(arr1*5)

[[0 1 2]
 [8 9 0]]

[[ 0  5 10]
 [40 45  0]]


#### Возведение массива (матрицы) в степень

Каждое значение массива возводится в степень __работает только в программировании__

In [ ]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr1, end='\n\n')

print(arr1**3)

[[1 2 3]
 [4 5 6]]

[[  1   8  27]
 [ 64 125 216]]


#### Умножение матриц

> Чтобы перемножить между собой две матрицы, количество __столбцов первой матрицы долнжно равнять количеству строк второй__

![](https://habrastorage.org/webt/ou/_g/wg/ou_gwgmqlsqlzlelu93s1q7vetw.png)

![](https://www.yotx.ru/Images/matrix-multiply-by-matrix-3.gif)

Матрица А размерности n\*m (n строк и m столбцов)
Матрица B размерности m\*k (m строк и k столбцов)

Матрица произведения будет иметь размерность (n*k)

In [ ]:
arr1 = np.array([[1, 2], [3, 4], [5, 6]])
arr2 = np.array([[1, 2], [3, 4]])
print(arr1)
print()
print(arr2)
print()
print(arr1 @ arr2)
print()
print(arr1.dot(arr2))

[[1 2]
 [3 4]
 [5 6]]

[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]
 [23 34]]

[[ 7 10]
 [15 22]
 [23 34]]


### Статистические характеристики

* среднее
* мода
* медиана

> Среднее (среднее арифметическое) - это отношение суммы элементов последовательности к их числу (количеству)

In [ ]:
list1 = [1, 2, 5, 6, 90, 100]

# находим среднее арифметическое математическим способом
print(f'Среднее арифметическое последовальности {list1} равняется {sum(list1)/len(list1)}')

# находим среднее арифметическое с помощью numpy
print(f'Среднее арифметическое последовальности {list1} равняется {np.mean(list1)}')


Среднее арифметическое последовальности [1, 2, 5, 6, 90, 100] равняется 34.0
Среднее арифметическое последовальности [1, 2, 5, 6, 90, 100] равняется 34.0


> Мода - показатель самого популярного значения в диапазоне

In [ ]:
from scipy import stats as st

list1 = [1, 2, 1, 1, 5, 4, 2, 1, 1, 5, 6, 90, 100]

# находим моду математическим способом
list_of_count = []
for i in list1:
  list_of_count.append(list1.count(i))
print(f'Мода последовательности {list1} равняется {list1[list_of_count.index(max(list_of_count))]}')

# находим моду с помощью scipy
print(f'Мода последовательности {list1} равняется {st.mode(list1)}')

Мода последовательности [1, 2, 1, 1, 5, 4, 2, 1, 1, 5, 6, 90, 100] равняется 1
Мода последовательности [1, 2, 1, 1, 5, 4, 2, 1, 1, 5, 6, 90, 100] равняется ModeResult(mode=1, count=5)


> Медиана - среднее число в отсортированном по возрастанию ряду, если ряд состоит из нечетного числа элементов, то медиана - средний элемент последовательности, однако если ряд состоит из четного числа элементов, то медиана - среднее арифметические двух центральных элементов

In [ ]:
# находим медиану математическим способом
list1 = [1, 1, 1, 2, 3, 4, 5, 1, 1, 1000]
list1.sort() # [1, 1, 1, 1, 1, 2, 3, 4, 5, 1000]

if len(list1) % 2 != 0:
  median = list1[len(list1)//2]
  print(f'Медиана нашего списка {list1} равна {median}')
else:
  median = (list1[len(list1)//2] + list1[len(list1)//2 - 1])/2
  print(f'Медиана нашего списка {list1} равна {median}')

Медиана нашего списка [1, 1, 1, 1, 1, 2, 3, 4, 5, 1000] равна 1.5


In [ ]:
# находим медиану в numpy
list2 = [1, 1, 1, 2, 3, 4, 5, 1, 1, 1000]
print(f'Медиана нашего списка {list2} равна {np.median(list2)}')

Медиана нашего списка [1, 1, 1, 2, 3, 4, 5, 1, 1, 1000] равна 1.5
