NumPy — библиотека с открытым исходным кодом для языка программирования Python. Возможности: поддержка многомерных массивов; поддержка высокоуровневых математических функций, предназначенных для работы с многомерными массивами.

![](https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/1024px-NumPy_logo_2020.svg.png)

### Работа с NumPy


In [ ]:
# первичная загрузка библиотеки для локального пользования
!pip install numpy

In [ ]:
# импортирование библиотеки для работы
import numpy as np

In [ ]:
# создаем одномерный массив

a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [ ]:
# создаем многомерный массив

b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


### Атрибуты массива в Numpy

In [ ]:
# узнаем количество измерений в массиве

print(b.ndim)

2


In [ ]:
# узнать размер массива в виде количества строк и столбцов

print(b.shape) # первая координата - число строк, вторая - число столбцов

(2, 3)


In [ ]:
# узнаем количество элементов в массиве

print(b.size)

6


In [ ]:
# узнаем тип данных элементов в массиве

print(b.dtype)

c = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)

print(c.dtype)

int64
float64


In [ ]:
# узнаем сумму элементов в массиве

print(c.sum())

21.0


In [ ]:
# зададим массив случайно

d = np.random.random((4, 5))

print(d)

[[0.3894871  0.57909681 0.24736785 0.39623581 0.55242044]
 [0.90661863 0.59619522 0.68526463 0.69773811 0.19755018]
 [0.83482319 0.59165634 0.28156517 0.72602213 0.24340113]
 [0.75462726 0.98360305 0.13749311 0.11966642 0.04973307]]


In [ ]:
# получаем минимальное число в массиве

print(b.min())

1


In [ ]:
# получаем максимальное число в массиве

print(b.max())

6


In [ ]:
# многомерный массив из нулей

e = np.zeros((3, 4))
print(e)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# многомерный массив из единиц

e = np.ones((5, 3))
print(e)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# массив с случайными числам

e = np.empty((6, 6))
print(e)

[[1.         1.         0.8        1.         1.         0.92941176]
 [0.62745098 1.         0.99607843 0.85098039 0.4627451  1.        ]
 [0.99607843 0.69803922 0.29803922 1.         0.99215686 0.55294118]
 [0.23529412 1.         0.98823529 0.30588235 0.16470588 1.        ]
 [0.89019608 0.10196078 0.10980392 1.         0.74117647 0.        ]
 [0.14901961 1.         0.50196078 0.         0.14901961 1.        ]]


In [ ]:
# массив с диапазоном между числами - аналог функции ragne

f = np.arange(50, 76, 5)

print(f)

[50 55 60 65 70 75]


In [ ]:
# создаем массив, в котором элементы находятся в некотором диапазоне

f = np.linspace(50, 80, 7) # разница между каждыми двумя идущими подряд числами - идентичная

print(f)

[50. 55. 60. 65. 70. 75. 80.]


In [ ]:
# изменяем количество измерений массива

f = np.arange(12).reshape(3, 4)

print(f)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Операции в NumPy

#### Сложение массивов (матриц)

![](https://www.yotx.ru/Images/matrix-addition-2.gif)


In [ ]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[10, 22, 54], [89, 29, 0]])

print(arr1, arr2, sep='\n\n')
print()
print(arr1 + arr2)

[[1 2 3]
 [4 5 6]]

[[10 22 54]
 [89 29  0]]

[[11 24 57]
 [93 34  6]]


#### Вычитание массива (матрицы)

![](https://www.yotx.ru/Images/matrix-subtraction-2.gif)

In [ ]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[10, 22, 54], [89, 29, 0]])

print(arr1, arr2, sep='\n\n')
print()
print(arr1 - arr2)

[[1 2 3]
 [4 5 6]]

[[10 22 54]
 [89 29  0]]

[[ -9 -20 -51]
 [-85 -24   6]]


#### Умножение массива (матрицы) на число

![](https://microexcel.ru/wp-content/uploads/2021/06/umnojenie-matritsy-na-chislo-1.png)

In [ ]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr1)
print()
print(arr1*5)

[[1 2 3]
 [4 5 6]]

[[ 5 10 15]
 [20 25 30]]


#### Возведение массива (матрицы) в степень

Каждое значение массива возводится в степень __работает только в программировании__

In [ ]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr1)
print()
print(arr1**2)

[[1 2 3]
 [4 5 6]]

[[ 1  4  9]
 [16 25 36]]


### Статистические характеристики

* Среднее
* Медиана
* Мода

> Среднее - это сумма чисел, разделенная на их количество

In [ ]:
arr = np.array([1, 2, 5, 6, 90, 100])

# решение с помощью математической операции
print(f'Среднее значение массива {arr} равняется {sum(arr)/len(arr)}')

# решение с помощью numpy
print(f'Среднее значение массива {arr} равняется {np.mean(arr)}')

Среднее значение массива [  1   2   5   6  90 100] равняется 34.0
Среднее значение массива [  1   2   5   6  90 100] равняется 34.0


> Мода - число, которое чаще всего встречается в массиве

In [ ]:
arr = [1, 2, 1, 2, 3, 4, 1, 1, 4, 5]

# математическое решение
c = list()
for i in arr:
  c.append(arr.count(i))

maximum = arr[c.index(np.max(c))]

print(maximum)

1


In [ ]:
from scipy import stats as st
# решение с помощью numpy
arr = np.array([1, 2, 1, 2, 3, 4, 1, 1, 4, 5])

print(f'Мода в массиве {arr} - это число {st.mode(arr)}')

Мода в массиве [1 2 1 2 3 4 1 1 4 5] - это число ModeResult(mode=1, count=4)


> Медиана - среднее число в отсортированном ряду, если ряд состоит из нечетного числа элементов, то берется центральный элемент, если из четного, то находится среднее от двух

In [ ]:
list1 = [1, 1, 1, 2, 3, 4, 1, 1, 4, 5]
list1.sort()

# математические вычисления
if len(list1) % 2 != 0:
  median = list1[len(list1)//2]
  print(f'Медиана нашего списка {list1} равняется {median}')
else:
  median = (list1[len(list1)//2] + list1[len(list1)//2 - 1])/2
  print(f'Медиана нашего списка {list1} равняется {median}')

Медиана нашего списка [1, 1, 1, 1, 1, 2, 3, 4, 4, 5] равняется 1.5


In [ ]:
list2 = [1, 1, 1, 2, 3, 4, 1, 1, 4, 5]
# вычисления с помощью numpy
print(f'Медиана списка {list2}, равняется {np.median(list2)}')

Медиана списка [1, 1, 1, 2, 3, 4, 1, 1, 4, 5], равняется 1.5
